/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package aap.dokumenter.app

import io.ktor.server.testing.*
import org.junit.jupiter.api.Test
import kotlin.test.assertTrue


class Test {
    @Test
    fun testmeg() {
        assertTrue(true)
    }
//    @Test
//    fun test() {
//        testApplication {
//            application {
//                dok()
//            }
//        }
//    }
}
