/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package aap.dokumenter.app

import io.ktor.server.testing.*
import org.junit.jupiter.api.Test


class Test {
//    @Test
//    fun test() {
//        testApplication {
//            application {
//                dok()
//            }
//        }
//    }
}
